### ISSUE TITLE
Use Webhook to send update when a team's score may have changed

### ISSUE THREAD

**Issue by dj21d** [Riebart/scorecard#8]
To better integrate with a live scoreboard webhooks could be used for updates.

**Comment by Riebart** [comment]
This probably makes more sense to post to an outgoing webhook when a score changes for a team based on a submission of a flag.

The submission logic could return the old and new data for a flag (on `dynamodb:UpdateItem`), and re-evaluate the timeouts on the flag based on old and new submission times. A post to the webhook would occur if the validity of those submission times is different (basically, re-tallying the score at the point in time of submission, but only for the submitted flag).

**Comment by Riebart** [comment]
Note that this won't provide events when the score changes due to expiry of a flag that needs to be reported continuously, so polling for those will still be necessary.

**Comment by Riebart** [comment]
Closing in favour of #14 unless there is a specific need for hooks.
